enum ROLES {
    user
    admin
}


Table user {
    id Autofield [pk]
    username CharField [note: 'max_length=150, unique=True']
    email EmailField [note: 'max_length=254']
    first_name CharField [note: 'max_length=150']
    last_name CharField [note: 'max_length=150']
    is_subscribed BooleanField [note: 'null=True, blank=True']
    role SCORES [note: 'Charfield(choices=ROLES']
}

Table tag {
    id Autofield [pk]
    name CharField [note: 'max_length=200']
    color CharField [note: 'max_length=7']
    slug SlugField [note: 'unique=True, max_length=200']
 }

Table ingredient {
    id Autofield [pk]
    name CharField [note: 'max_length=200']
    measurement_unit CharField [note: 'max_length=200']
}

Table recipe {
    id Autofield [pk]
    author ForeignKey [ref: > user.id, note: 'on-delete.CASCADE, related_name=recipes']
    name CharField [note: 'max_length=200']
    text TextField
    cooking_time PositiveSmallIntegerField
    image ImageField
    is_in_shopping_cart BooleanField
    is_favourited BooleanField
}

Table tag_recipe {
    tag_id ForeignKey [ref: > tag.id, note: 'on-delete:CASCADE, related_name=tag_recipe']
    recipe_id ForeignKey [ref: > recipe.id, note: 'on-delete:CASCADE, related_name=tag_recipe']
}

Table ingredient_recipe {
    ingredient_id ForeignKey [ref: > ingredient.id, note: 'on-delete:CASCADE, related_name=ingredient_recipe']
    recipe_id ForeignKey [ref: > recipe.id, note: 'on-delete:CASCADE, related_name=ingredient_recipe']
}

Table amount_ingredient_in_recipe {
    ingredient_id OneToOneField [ref: > ingredient.id, note: 'on-delete:CASCADE, related_name=amount_ingredient']
    recipe_id ForeignKey [ref: > recipe.id, note: 'on-delete:CASCADE, related_name=amount_recipe']
    quantity PositiveSmallIntegerField
}

Table subscribe {
    user_id ForeignKey [ref: > user.id, note: 'on_delete:CASCADE, related_name=subscriber']
    subscriber_id ForeignKey [ref: > user.id, note: 'on_delete:CASCADE, related_name=subscribing']
}