version: '3.3'

volimes:
  pg_data:
  static:
  media:
  redoc:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
     - pg_data:/var/lib/postgresql/data
  backend:
    image: siktorovich/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: siktorovich/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - redoc:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/